INSERT INTO users (login, password, lastname, firstname) VALUES ('daniel', 'daniel', 'Kulesz', 'Daniel');    
INSERT INTO users (login, password, lastname, firstname) VALUES ('sajib', 'sajib', 'Mohammad', 'Sajib'); 


INSERT INTO TOPIC_BASED_EXAMS (NAME, META_INFO, YEAR, MONTH, CREATED_DATE) VALUES ('Bachelor SWT, Modul Einführung in die Softwaretechnik', 'EST 2011 H', 2012, 8, '2012-08-20');   


INSERT INTO TBE_TOPICS (NAME, TOPIC_BASED_EXAM_ID) VALUES ('Grundlagen', 1);    
INSERT INTO TBE_TOPICS (NAME, TOPIC_BASED_EXAM_ID) VALUES ('Qualität, Kosten, Organisation', 1);    
INSERT INTO TBE_TOPICS (NAME, TOPIC_BASED_EXAM_ID) VALUES ('Risiken, QS, Spezifikation', 1);    
INSERT INTO TBE_TOPICS (NAME, TOPIC_BASED_EXAM_ID) VALUES ('Entwurf, Test', 1); 


INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Röntgenstrahlen wurden Ihnen als eine technische Innovation des 19. Jahrhunderts vorgestellt, die in mancher Hinsicht mit Software vergleichbar ist. Welche Verbesse- rungen, die man auf die Software übertragen könnte (und sollte), hat es beim Umgang mit Röntgenstrahlen gegeben? Nennen Sie drei.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br />•<br /> <br /> •<br /> <br /> •<br /> <br />', 2012, '2012-08-16', 1,3);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Dijkstra hat eine berühmte Aussage zum Programmtest gemacht. Welche ist das?<br /> Begründen Sie seine Aussage.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br /> <br />', 2012, '2012-08-16', 1,3);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('In der Vorlesung wurde „Werkstoff“ als Metapher verwendet. Für was?<br /> Begründen Sie, warum diese Metapher geeignet ist.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 1,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Wann und von wem wurde der Begriff „Software Engineering“ geschaffen?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 1,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Sie bereiten eine Entscheidung Ihrer Firma vor: Eine benötigte Software kann<br /> entweder entwickelt oder als Standardprodukt gekauft werden. Die Kosten bis zur<br /> Inbetriebnahme sind in beiden Fällen etwa gleich hoch, und auch die Qualität wird sich<br /> kaum unterscheiden. Welches wichtige Argument spricht für den Kauf?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />', 2012, '2012-08-16', 1,1);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Was versteht man unter einem quantifizierten Qualitätsmodell, und wie kann man es<br /> nutzen?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />', 2012, '2012-08-16', 2,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('In einem Softwareprojekt gibt es viele Rollen. Die Zuordnung zwischen Personen und<br /> Rollen kann ganz unterschiedlich sein. Nennen Sie zwei Beispiele für Rollen, die meist<br /> von genau einer Person wahrgenommen werden, die nur diese eine Rolle hat.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 2,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Bei welcher Art von Projekten ist das Marketing ein wichtiger Partner?<br /> Welche Aufgabe hat das Marketing in diesen Projekten?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 2,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Welche Voraussetzungen müssen erfüllt sein, damit mehrere Personen ein<br /> demokratisches Team bilden können? Nennen Sie zwei.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 2,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Welche Funktion hat der Projekteigentümer?<br /> Was ist die schwerstwiegende Entscheidung, die er treffen kann?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 2,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Bei der Planung eines Softwareprojekts ändern Sie den Zeitaufwand für eines der<br /> Arbeitspakete von 15 auf 10 Tage. Ihr Netzplan-Werkzeug meldet Ihnen, dass damit<br /> die Gesamtdauer um drei Tage gesunken ist. Was können Sie über den kritischen<br /> Pfad im Netzplan vor und nach der Änderung aussagen?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 2,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Von COCOMO gibt es zwei Versionen. Wann wurden sie publiziert, und wer hat sie<br /> (allein bzw. mit Koautoren) geschaffen?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> Jahr (V1):                      Jahr (V1):                        Name:  <br /> <br />', 2012, '2012-08-16', 2,2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Sie haben die Möglichkeit, ein Risiko zu versichern, das etwa in jedem hundertsten Projekt eintritt und in diesem Fall einen Schaden von 2'000'000 € verursacht. Was wird Sie die Versicherung ungefähr kosten, wenn die Versicherungsgesellschaft das Risiko ähnlich wie Sie einschätzt?<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> <br /> <br /> <br /> <br /> <br /> <br />', 2012, '2012-08-16', 3, 2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Welche Aufgaben hat der Qualitätssicherungs-Ingenieur (sinnvollerweise)? Nennen Sie drei.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> •<br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 3, 2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Sie vertreten gegenüber einem Kunden ein Software-Haus. Der Kunde übergibt Ihnen den folgenden Text, den er als Spezifikation bezeichnet. Sie sollen die einzelnen Aussagen den Dokumenten zuordnen, in die sie sinnvollerweise gehören. Wo Sie mehrere Möglichkeiten sehen, können Sie eine (sinnvolle) Wahl treffen. Überlegen Sie im Zweifel, in welchem Schritt diese Information erhoben werden sollte. Anmerkung: Es wird hier unterstellt, dass eine sehr differenzierte Dokumentation entsteht. Sie müssen also eine präzise Wahl treffen. Hinter jedem Satz bleibt Raum für Ihre Zuordnung. Das Muster deutet an, wie Sie den Text kommentieren sollen. Muster: Heute ist schönes Wetter Ihre Zuordnung: Gehört hier überhaupt nicht rein! <br /> (1) Die Hörsaal-Verwaltung (HV) ist ein benutzerfreundliches Programm,<br /> <br /> (2) das nach den Grundsätzen des Information Hiding aufgebaut ist;<br /> <br /> (3) Bislang hat der Stundenplan-Administrator die Planung auf einer Stecktafel gemacht.<br /> <br /> (4) Der Stundenplan-Administrator ist diejenige Person in der Fakultät, die den Stundenplan erstellt.<br /> <br /> (5) Es kann sich auch um eine Gruppe von bis zu drei Personen handeln.<br /> <br /> (6) Mit der HV soll der Stundenplan-Administrator auch die einmalige Benutzung von Räumen (z.B. für Prüfungen oder Vorträge) koordinieren.<br /> <br /> (7) Die Komponenten für die Dauerbelegung sollen aber zuerst entwickelt werden und schon im kommenden Sommersemester verfügbar sein.<br /> <br /> (8) Dazu werden wir spätestens am 1. November vollständige Listen aller Lehrveran- staltungen in den beiden vergangenen Semestern in elektronischer Form (ASCII) vorlegen.<br /> <br /> (9) Bei reinen Abfragen ist eine Antwort innerhalb von 1 s garantiert.<br /> <br /> (10) Alle Teile des Programms, die den Abfrage-Dialog realisieren, stehen im Modul „Abfragen“.<br /> <br /> (11) Aus Sicherheitsgründen darf nur von den Rechnern der Fakultät aus zugegriffen werden.<br /> <br /> (12) Die Fakultät wird zukünftig bis zu 30 Dozenten haben.<br /> <br />', 2012, '2012-08-16', 3, 8);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Die Feststellung „Qualtiät kann man nicht ins Produkt hineinprüfen.“ steht scheinbar im Widerspruch zur Erfahrung, dass Firmen bessere Qualität liefern, wenn dort systema- tisch geprüft wird. Erklären Sie, warum beides stimmt.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> •<br /> <br /> <br />', 2012, '2012-08-16', 3, 2);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Emma hat den Auftrag, ein gegebenes System neu zu implementieren, wobei die Oberfläche unverändert bleiben soll. Karl soll auf einem Spezialprozessor mit sehr kargem Befehlssatz einfache Routinen implementieren, die später von den Anwendern durch eine Assembler-ähnliche Sprache verwendet werden können. Beispielsweise fehlen auf dem Prozessor Multiplikation und Division.<br /> <br /> Welche Vorgehensrichtung ist für Emma sinnvoll? Welche für Karl? Begründen Sie Ihre Wahl (sehr kurz, nur ein Satz oder Halbsatz).<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 4, 3);
INSERT INTO TBE_QUESTIONS (NAME, CREATEDYEAR, CREATEDDATE, TBE_TOPIC_ID, POINT) VALUES ('Sie haben die Aufgabe, in einem Programmsystem die Kopplung zu reduzieren. Dazu müssen Sie vor allem die starke, „schlimme“ Kopplung erkennen. Nennen Sie zwei zuverlässige Indizien für starke Kopplung.<br /> ----------------------------------------------------------------------------------------------------------------------------------------------------------------<br /> •<br /> <br /> <br /> <br /> •<br /> <br /> <br /> <br />', 2012, '2012-08-16', 4, 2);

